#ELCONFIDENCIAL
CONFIDENCIAL_DATA_PATH = "data/confidencial.json"
CONFIDENCIAL_URL = "https://www.elconfidencial.com/"
CONFIDENCIAL_TITLE_SELECTOR = "title"
CONFIDENCIAL_PARAGRAPHS_SELECTOR = "main #news-body-cc p"
CONFIDENCIAL_LINK_SELECTOR = "a"

#ELPAIS
PAIS_DATA_PATH = "data/elpais.json"
PAIS_URL = "https://www.elpais.com/"
PAIS_TITLE_SELECTOR = "title"
PAIS_PARAGRAPHS_SELECTOR = "article #cuerpo p"
PAIS_LINK_SELECTOR = "a"

#ELABC
ABC_DATA_PATH = "data/abc.json"
ABC_URL = "https://www.abc.es/"
ABC_TITLE_SELECTOR = "title"
ABC_PARAGRAPHS_SELECTOR = "p.voc-p"
ABC_LINK_SELECTOR = "a"

#LAVANGUARDIA
VANGUARDIA_DATA_PATH = "data/vanguardia.json"
VANGUARDIA_URL = "https://www.lavanguardia.com/"
VANGUARDIA_TITLE_SELECTOR = "title"
VANGUARDIA_PARAGRAPHS_SELECTOR = "article #cuerpo p"
VANGUARDIA_LINK_SELECTOR = "p"

#ELESPANOL
ESPANOL_DATA_PATH = "data/elespanol.json"
ESPANOL_URL = "https://www.elespanol.com/"
ESPANOL_TITLE_SELECTOR = "title"
ESPANOL_PARAGRAPHS_SELECTOR = "article #article_body p"
ESPANOL_LINK_SELECTOR = "a"

#DICTIONARY
NEWS_DICT = {
        "elconfidencial": (CONFIDENCIAL_DATA_PATH, CONFIDENCIAL_URL, CONFIDENCIAL_TITLE_SELECTOR, CONFIDENCIAL_PARAGRAPHS_SELECTOR, CONFIDENCIAL_LINK_SELECTOR),
        "elpais": (PAIS_DATA_PATH, PAIS_URL, PAIS_TITLE_SELECTOR, PAIS_PARAGRAPHS_SELECTOR, PAIS_LINK_SELECTOR),
        "abc": (ABC_DATA_PATH, ABC_URL, ABC_TITLE_SELECTOR, ABC_PARAGRAPHS_SELECTOR, ABC_LINK_SELECTOR),
        "lavanguardia": (VANGUARDIA_DATA_PATH, VANGUARDIA_URL, VANGUARDIA_TITLE_SELECTOR, VANGUARDIA_PARAGRAPHS_SELECTOR, VANGUARDIA_LINK_SELECTOR),
        "elespanol": (ESPANOL_DATA_PATH, ESPANOL_URL, ESPANOL_TITLE_SELECTOR, ESPANOL_PARAGRAPHS_SELECTOR, ESPANOL_LINK_SELECTOR)
    }